### ISSUE TITLE
Create address function is not working

### ISSUE THREAD

**Issue by umarjavedse** [saudslm/recharge-api-node#2]
Hi, 
I'm using this library in my project and I found issue in create address function. Create address endpoint in not according to Recharge API.
Endpoint should be "/customers/<int:customer_id>/addresses"
but currently used endpoint is "/addresses".
Please have a look on it. Thanks in Advance

**Comment by saudslm** [comment]
@umarjavedse 
Thanks for the feedback. I have fixed this issue in the latest patch.

I ended up removing **create** function from _address_  and moved it under _CustomerAddress_. I've updated in the documentation.

**Comment by umarjavedse** [comment]
@saudslm 
Great! It seems like work fine. I'll let you know if any other issue raise.
By the way, bundle of thanks for your quick fix.
