### ISSUE TITLE
Unskip charges endpoint is wrong

### ISSUE THREAD

**Issue by umarjavedse** [saudslm/recharge-api-node#3]
Hi, 
I'm using this library in my project and you have done a great job. I found issue in unskip charge function. Unskip charges endpoint in not according to Recharge API.
Endpoint should be "/charges/<charge_id>/unskip"
but currently used endpoint is "/charges/<charge_id>/skip".
Please replace "unskip" with "skip" in following function or I can create PR.
Thanks in advance.

**Comment by saudslm** [comment]
@umarjavedse 
that's a silly mistake. haha
should be fixed in the latest patch.

**Comment by umarjavedse** [comment]
hi @saudslm ,
Thanks for you response. When will latest patch is expected ?

**Comment by saudslm** [comment]
@umarjavedse 
just updated the npm package v1.1.1

**Comment by umarjavedse** [comment]
@saudslm 
Great! works , Thanks man
