### ISSUE TITLE
getPaymentSources(id) function is not returning response

### ISSUE THREAD

**Issue by umarjavedse** [saudslm/recharge-api-node#4]
Hi @saudslm ,
customer.getPaymentSources(id) function not returning response because array key is change from Recharge response in body.
Please replace code in /resources/customer on line 18 with 
`return this.recharge.request(url, 'GET', 'payment_sources');`
Produce this bug after lot of finding :)
Waiting new release. Thanks

**Comment by saudslm** [comment]
@umarjavedse 
Just published a new patch v1.1.2, should be fixed now.
Thanks for the feedback.

**Comment by umarjavedse** [comment]
@saudslm 
Perfect! Thanks.
