### ISSUE TITLE
discount function not working

### ISSUE THREAD

**Issue by umarjavedse** [saudslm/recharge-api-node#5]
Hi @saudslm ,
`discount` function is not working because it is not defined under `map` object in /resources/index.js.
I also commented on previous commit, please check those as well. Thanks for co-operation.

**Comment by saudslm** [comment]
@umarjavedse 
Just published a new patch v1.1.2, should be fixed now.
Thanks for the feedback.

**Comment by umarjavedse** [comment]
@saudslm 
Great! Thanks. 
I have a question, are you planning to add `checkout` functionality? Please let me know about that.

**Comment by saudslm** [comment]
@umarjavedse 
I am planning to add checkout, would you mind adding it as a new/requested feature here on github.

**Comment by umarjavedse** [comment]
@saudslm 
Yes sure!
