### ISSUE TITLE
Checkout feature request

### ISSUE THREAD

**Issue by umarjavedse** [saudslm/recharge-api-node#6]
Hi @saudslm ,
This is request for new feature.
Please add 'checkout' functions as well in this package. [Checkouts](https://developer.rechargepayments.com/?shell#checkouts) still in Beta version on ReCharge API as well but it would be great if `checkout` will also added in this package. 
Thanks for your co-operation.

**Comment by saudslm** [comment]
Hi @umarjavedse 

Checkout endpoints have been added in v1.1.3

**Comment by umarjavedse** [comment]
Hi @saudslm ,
Glad to hear, I'll use `checkout` in my app and will let you know if found any issue.
Thanks.
