### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by diegoaguilar** [saudslm/recharge-api-node#8]
May extend this issue description, but in a few words I need to know if you've implemented pagination.

**Comment by saudslm** [comment]
@diegoaguilar yes, pagination is implemented. All functions for respective end points accept the same request parameters as an object.

**Comment by diegoaguilar** [comment]
Hmm can you provide an example on how to automatically paginate? 

I implemented a recursive function where I'd request `count()` first and then pass  `page` incrementally until the total of resources would have been fetched.

**Comment by saudslm** [comment]
@diegoaguilar 

Here's a simple example for list address end point.

```javascript
recharge.address.count().then(async count => {
    const limit = 250;
    const noOfPages = Math.ceil(count / limit);
    let addresses = [], singlePageResults = [];
    for(let page = 1; page <= noOfPages; page++){
        singlePageResults = await recharge.address.list({page, limit});
        addresses.push(...singlePageResults);
    }
}).catch((e) => {
    console.log('well', e.name, e.response.statusCode);
});
```
